name: helm-upgrade
run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'Environment to deploy'
        type: string
      version:
        required: true
        type: string
      helm-values-path:
        type: string
        default: './kube2py/values.yaml'


jobs:

  deploy-helm:
      name: ${{ inputs.environment }}
      runs-on: ubuntu-latest
      environment: ${{ inputs.environment }}

      steps:

      - uses: actions/download-artifact@v4
        with:
          name: helm-package
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: helm-artifact
          path: .

      - name: Set Up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Set Up Kubectl
        uses: azure/setup-kubectl@v4

      - uses: azure/login@v2
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ vars.AZURE_CLUSTER_NAME }}

      # - name: Docker Pull Image
      #   run: |
      #     docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}



      - name: Deploy Helm To Development
        run: |
          helm upgrade --install --atomic --wait --timeout 3600s --debug kube2py ./kube2py-*.tgz \
          -f ${{ inputs.helm-values-path }} \
          --set primary.service.annotations="{}" \
          --set-string mysql.configs.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
          --set-string mysql.configs.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
          --set-string mysql.configs.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
          --set-string kube2py.secrets.password="${{ secrets.KUBE2PY_PASSWORD }}" \
          --set-string kube2py.secrets.login="${{ secrets.KUBE2PY_LOGIN }}" \
          --set-string kube2py.secrets.DB_CONNECTION="${{ secrets.DB_CONNECTION }}" \
          --set kube2py.image.version=2.0.0
